version: '3.8'

services:
  postgres_db:
    # image: postgres:15-alpine
    image: pgvector/pgvector:pg15
    container_name: project_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: myproject_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: